const POSITIONS=['GS','GA','WA','C','WD','GD','GK'];
const defaultPlayers=['Mia','Ava','Ruby','Sophie','Ella','Zoe','Grace','Chloe','Lily','Evie'].map((name,i)=>({id:crypto.randomUUID(),name,preferred:POSITIONS[i%7]}));
const state={players:JSON.parse(localStorage.getItem('pm_players')||'null')||defaultPlayers,plays:JSON.parse(localStorage.getItem('pm_plays')||'[]'),lines:[],tool:'move',ourScore:0,oppScore:0};
const save=()=>{localStorage.setItem('pm_players',JSON.stringify(state.players));localStorage.setItem('pm_plays',JSON.stringify(state.plays));updateStats();};
function nav(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===id && b.closest('.bottom-nav')));if(id==='team')renderPlayers();if(id==='court')renderCourt();if(id==='playbook')renderPlays();if(id==='rotations')renderRotations();if(id==='game')renderGame();window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));
function updateStats(){teamCount.textContent=1;playCount.textContent=state.plays.length;playerCount.textContent=state.players.length;}
function renderPlayers(){playerList.innerHTML='';state.players.forEach(p=>{const el=document.createElement('div');el.className='player-card';el.innerHTML=`<div class="avatar">${p.name.slice(0,1)}</div><div class="meta"><strong>${p.name}</strong><br><small>Preferred: ${p.preferred}</small></div><button class="ghost small">Edit</button>`;el.querySelector('button').onclick=()=>{const name=prompt('Player name',p.name);if(name)p.name=name;const pos=prompt('Preferred position',p.preferred);if(POSITIONS.includes(pos?.toUpperCase()))p.preferred=pos.toUpperCase();save();renderPlayers();};playerList.appendChild(el)});}
addPlayer.onclick=()=>{const name=prompt('Player name');if(!name)return;state.players.push({id:crypto.randomUUID(),name,preferred:'C'});save();renderPlayers();};
function courtPositions(){return [[16,50],[25,30],[37,68],[50,50],[63,32],[75,70],[84,50],[12,87],[50,87],[88,87]]}
function renderCourt(){courtBoard.querySelectorAll('.token').forEach(x=>x.remove());const coords=courtPositions();state.players.slice(0,10).forEach((p,i)=>{const t=document.createElement('div');t.className='token'+(i>6?' bench':'');t.textContent=i<7?POSITIONS[i]:'B';t.title=p.name;t.style.left=coords[i][0]+'%';t.style.top=coords[i][1]+'%';t.dataset.player=p.id;makeDraggable(t);courtBoard.appendChild(t)});drawLines();}
function makeDraggable(el){let drag=false;const move=e=>{if(!drag)return;const r=courtBoard.getBoundingClientRect();const p=e.touches?e.touches[0]:e;const x=Math.max(0,Math.min(100,(p.clientX-r.left)/r.width*100));const y=Math.max(0,Math.min(100,(p.clientY-r.top)/r.height*100));el.style.left=x+'%';el.style.top=y+'%';};el.addEventListener('pointerdown',e=>{if(state.tool==='move'){drag=true;el.setPointerCapture?.(e.pointerId)}else{handleLineClick(el)}});el.addEventListener('pointermove',move);el.addEventListener('pointerup',()=>drag=false);}
let lineStart=null;function handleLineClick(el){if(!lineStart){lineStart=el;el.style.outline='3px solid #facc15';return}const a={x:parseFloat(lineStart.style.left),y:parseFloat(lineStart.style.top)},b={x:parseFloat(el.style.left),y:parseFloat(el.style.top)};state.lines.push({a,b,type:state.tool});lineStart.style.outline='';lineStart=null;drawLines();}
function drawLines(){courtLines.innerHTML='';state.lines.forEach(l=>{const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',l.a.x+'%');line.setAttribute('y1',l.a.y+'%');line.setAttribute('x2',l.b.x+'%');line.setAttribute('y2',l.b.y+'%');line.setAttribute('stroke',l.type==='pass'?'#fff':'#172554');line.setAttribute('stroke-width','3');line.setAttribute('stroke-dasharray',l.type==='lead'?'8 6':'0');courtLines.appendChild(line)});}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;document.querySelectorAll('.tool[data-tool]').forEach(x=>x.classList.toggle('active',x===b));});clearLines.onclick=()=>{state.lines=[];drawLines()};
savePlay.onclick=()=>{const name=playName.value.trim()||`Play ${state.plays.length+1}`;const tokens=[...courtBoard.querySelectorAll('.token')].map(t=>({player:t.dataset.player,label:t.textContent,x:t.style.left,y:t.style.top}));state.plays.unshift({id:crypto.randomUUID(),name,note:playNote.value.trim(),tokens,lines:[...state.lines],created:new Date().toISOString()});save();playName.value='';playNote.value='';alert('Play saved to your playbook.');};
function renderPlays(){playList.innerHTML=state.plays.length?'':'<div class="card"><p>No plays yet. Build your first play on the Court tab.</p></div>';state.plays.forEach(p=>{const el=document.createElement('div');el.className='play-item';el.innerHTML=`<div><strong>${p.name}</strong><p>${p.note||'No coaching note'}</p></div><button class="ghost small">Delete</button>`;el.querySelector('button').onclick=()=>{state.plays=state.plays.filter(x=>x.id!==p.id);save();renderPlays()};playList.appendChild(el)});}
function renderRotations(){const periods=+matchFormat.value;rotationGrid.innerHTML='';for(let q=0;q<periods;q++){const card=document.createElement('div');card.className='card period-card';card.innerHTML=`<h3>${periods===4?'Quarter '+(q+1):'Half '+(q+1)}</h3>`;POSITIONS.forEach((pos,i)=>{const row=document.createElement('div');row.className='rotation-row';row.innerHTML=`<span>${pos}</span><select data-q="${q}" data-pos="${pos}">${state.players.map((p,j)=>`<option value="${p.id}" ${j===((i+q)%state.players.length)?'selected':''}>${p.name}</option>`).join('')}</select>`;card.appendChild(row)});rotationGrid.appendChild(card)}}
matchFormat.onchange=renderRotations;autoRotate.onclick=()=>renderRotations();
function renderGame(){gameLineup.innerHTML='';POSITIONS.forEach((pos,i)=>{const p=state.players[i];const d=document.createElement('div');d.innerHTML=`<strong>${pos}</strong><br>${p?.name||'Unassigned'}`;gameLineup.appendChild(d)});ourScore.textContent=state.ourScore;oppScore.textContent=state.oppScore;}
ourPlus.onclick=()=>{state.ourScore++;renderGame()};oppMinus.onclick=()=>{state.oppScore=Math.max(0,state.oppScore-1);renderGame()};oppScore.onclick=()=>{state.oppScore++;renderGame()};
let seconds=900,timerId=null;function showTimer(){timer.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`};timerToggle.onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;timerToggle.textContent='Start'}else{timerId=setInterval(()=>{if(seconds>0){seconds--;showTimer()}else{clearInterval(timerId);timerId=null}},1000);timerToggle.textContent='Pause'}};
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});installBtn.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.hidden=true}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});updateStats();renderPlayers();renderCourt();