// Playmaker Standard Library — 10 coachable patterns with instructional step mode.
(()=>{const board=document.getElementById('courtBoard'),watch=document.getElementById('demoGame'),next=document.getElementById('nextDemoPlay'),back=document.getElementById('prevDemoStep'),step=document.getElementById('nextDemoStep'),select=document.getElementById('demoPlaySelect'),panel=document.getElementById('demoPanel'),title=document.getElementById('demoTitle'),note=document.getElementById('demoNote'),stepLabel=document.getElementById('demoStep');if(!board||!watch)return;
const names=['Split','Stack','Switch','Diamond','Clear','Baseline','Triangle','Slingshot','Wave','Reset'];
const notes=['WA and GA split to opposite channels to create two first-pass options.','WA and GA start together then break apart, forcing defenders to choose.','Show one channel, then cross and attack the opposite channel.','Maintain four connected passing options around the ball carrier.','GA clears space to release GS into the primary scoring lane.','GS clears across the circle while GA attacks the baseline-side space.','GS, GA and WA rotate as a three-point passing shape around the circle.','Move wide, switch quickly through centre, then accelerate into attack.','Sequential leads: present, clear and replace so the next receiver arrives on time.','Release pressure backwards or sideways, restore spacing, then rebuild.'];
const base=[[12,50],[27,38],[38,66],[50,50],[62,32],[75,68],[88,50]];
const end=[[[25,50],[58,34],[70,62],[79,49],[66,30],[80,66],[88,50]],[[24,50],[61,39],[69,58],[78,48],[67,31],[80,65],[88,50]],[[25,50],[64,60],[70,32],[79,50],[67,30],[80,66],[88,50]],[[25,50],[58,35],[67,65],[76,50],[62,29],[79,68],[88,50]],[[87,50],[72,68],[65,43],[57,50],[45,30],[30,67],[15,50]],[[84,65],[76,36],[68,55],[58,49],[45,31],[30,67],[15,50]],[[84,50],[76,67],[70,31],[61,50],[47,31],[31,67],[15,50]],[[28,50],[65,41],[77,24],[81,50],[67,69],[80,66],[88,50]],[[28,50],[63,40],[72,63],[81,49],[68,30],[80,66],[88,50]],[[28,50],[58,40],[70,62],[78,49],[60,28],[78,67],[88,50]]];
const passSets=[[[1,3,2],[2,2,1],[3,1,0]],[[1,3,2],[2,2,1],[3,1,0]],[[1,3,1],[2,1,2],[3,2,0]],[[1,3,2],[2,2,1],[3,1,0]],[[1,3,2],[2,2,1],[3,1,0]],[[1,3,2],[2,2,1],[3,1,0]],[[1,3,2],[2,2,1],[3,1,0]],[[1,3,2],[2,2,3],[3,3,1],[4,1,0]],[[1,3,2],[2,2,1],[3,1,0]],[[1,3,2],[2,2,3],[3,3,1],[4,1,0]]];
const phaseNames=['Setup','First lead','First pass','Second phase','Finish'];
const phaseCues=[
['Hold width and depth. C owns the centre pass; WA/GA stay ready to split.','WA and GA separate hard into different channels.','C chooses the cleaner option; receiver meets the ball.','Second receiver re-times into space created by the first lead.','Feed the best scoring option without collapsing spacing.'],
['Create a compact stack without blocking each other.','Top player breaks first; second player delays half a beat.','Hit the first clean release, not the pre-called option.','The unused player rolls into the next lane.','Finish with width around the circle.'],
['Show one side strongly enough to move the defence.','Primary cutters cross and exchange channels.','Ball goes to the player who wins the switch.','C and the spare attacker fill behind the cross.','Attack the vacated lane quickly.'],
['Keep four connected points around the ball.','Nearest two options present at different depths.','Take the simplest pass that preserves the diamond.','Rotate the shape around the new ball carrier.','Enter the circle with two live outlets.'],
['GA clears decisively; do not hover in GS space.','GS holds then drives into the lane GA creates.','Feed away from GK pressure.','GA re-offers as the second scoring option.','Maintain separation between GS and GA.'],
['GS clears across the circle early.','GA drives hard toward baseline-side space.','Feed the body side away from GD.','GS balances across the circle for rebound/second option.','Finish with both shooters occupying different lines.'],
['Build a clear triangle around the circle edge.','One point moves, the next fills, the third holds.','Pass around the edge rather than forcing centre traffic.','Rotate again after the catch.','Feed when GK/GD are forced to turn.'],
['Start with width so the defence has to stretch.','WA pushes wide while C prepares the switch.','Move the ball wide first.','Switch quickly back through C/GA.','Accelerate into the opposite attacking channel.'],
['Only one main lead should arrive at a time.','First receiver presents; next receiver waits.','Ball follows the first successful lead.','First receiver clears and the next player replaces.','Keep the sequence flowing into circle entry.'],
['Recognise the lane is closed before forcing it.','Offer a safe lateral/back outlet.','Use the reset pass to remove immediate pressure.','Rebuild width and depth around the new ball carrier.','Re-attack once defenders have shifted.']];
const activeSets=[[[3,2,1],[2,1],[3,2],[2,1,0],[1,0]],[[2,1,3],[2,1],[3,2],[2,1],[1,0]],[[3,1,2],[1,2],[3,1],[1,2,0],[2,0]],[[3,2,1,4],[2,1],[3,2],[2,1,0],[1,0]],[[1,0,2],[1,0],[2,1],[1,0],[1,0]],[[0,1,2],[0,1],[2,1],[1,0],[1,0]],[[0,1,2],[0,1,2],[2,1],[1,0,2],[1,0]],[[3,2,1],[2,3],[3,2],[3,1],[1,0]],[[3,2,1],[2],[3,2],[2,1],[1,0]],[[3,2,4],[4,3],[3,4],[3,2,1],[1,0]]];
const plays=names.map((name,i)=>{const frames=[];for(let s=0;s<5;s++){const f=s/4;frames.push(base.map((p,j)=>[p[0]+(end[i][j][0]-p[0])*f,p[1]+(end[i][j][1]-p[1])*f]))}return{name:`${String(i+1).padStart(2,'0')} · ${name}`,note:notes[i],frames,passes:passSets[i],dur:6000,cues:phaseCues[i],active:activeSets[i]}});
let pi=0,si=0,running=false,raf=null,startAt=0;const ball=document.createElement('div');ball.className='demo-ball';board.appendChild(ball);const tokens=()=>[...board.querySelectorAll('.token:not(.defender-token)')].slice(0,7),portrait=()=>matchMedia('(orientation:portrait)').matches&&matchMedia('(max-width:520px)').matches,tx=p=>portrait()?{x:p[1],y:p[0]}:{x:p[0],y:p[1]},mix=(a,b,f)=>a+(b-a)*f;
plays.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=p.name;select?.appendChild(o)});
function highlight(indices=[]){tokens().forEach((t,i)=>t.classList.toggle('teaching-active',indices.includes(i)))}
function setFrame(idx){const p=plays[pi],fr=p.frames[idx];tokens().forEach((t,i)=>{const q=tx(fr[i]);t.style.left=q.x+'%';t.style.top=q.y+'%'});highlight(p.active[idx]||[]);si=idx;panel.hidden=false;title.textContent=`${p.name} · ${phaseNames[idx]}`;note.textContent=p.cues[idx]||p.note;stepLabel.textContent=`Step ${idx+1} of ${p.frames.length} · ${phaseNames[idx]}`;ball.style.display='none'}
function animate(now){if(!running)return;const p=plays[pi],e=now-startAt;if(e>=p.dur){running=false;watch.querySelector('b').textContent='Watch';setFrame(p.frames.length-1);return}const span=p.dur/(p.frames.length-1),idx=Math.min(3,Math.floor(e/span)),f=(e-idx*span)/span,a=p.frames[idx],b=p.frames[idx+1];tokens().forEach((t,i)=>{const q=tx([mix(a[i][0],b[i][0],f),mix(a[i][1],b[i][1],f)]);t.style.left=q.x+'%';t.style.top=q.y+'%'});highlight([...(p.active[idx]||[]),...(p.active[idx+1]||[])]);title.textContent=`${p.name} · ${phaseNames[idx+1]}`;note.textContent=p.cues[idx+1]||p.note;stepLabel.textContent=`Playing · ${phaseNames[idx+1]}`;let shown=false;p.passes.forEach(([phase,from,to])=>{const pt=phase*span-350,d=500;if(e>=pt&&e<=pt+d&&!shown){const aa=tx(a[from]),bb=tx(b[to]),pf=(e-pt)/d;ball.style.left=mix(aa.x,bb.x,pf)+'%';ball.style.top=mix(aa.y,bb.y,pf)+'%';ball.style.display='block';shown=true}});if(!shown)ball.style.display='none';raf=requestAnimationFrame(animate)}
function stop(){running=false;if(raf)cancelAnimationFrame(raf);ball.style.display='none';watch.querySelector('b').textContent='Watch'}function choose(i){stop();pi=(i+plays.length)%plays.length;si=0;if(select)select.value=pi;setFrame(0)}
select?.addEventListener('change',()=>choose(Number(select.value)));watch.addEventListener('click',()=>{if(running){stop();setFrame(si);return}running=true;startAt=performance.now();watch.querySelector('b').textContent='Pause';panel.hidden=false;raf=requestAnimationFrame(animate)});step?.addEventListener('click',()=>{stop();setFrame(Math.min(plays[pi].frames.length-1,si+1))});back?.addEventListener('click',()=>{stop();setFrame(Math.max(0,si-1))});next?.addEventListener('click',()=>choose(pi+1));choose(0);
})();