// Playmaker Standard Library — 10 coachable patterns with Watch + Step mode.
(()=>{const board=document.getElementById('courtBoard'),watch=document.getElementById('demoGame'),next=document.getElementById('nextDemoPlay'),back=document.getElementById('prevDemoStep'),step=document.getElementById('nextDemoStep'),select=document.getElementById('demoPlaySelect'),panel=document.getElementById('demoPanel'),title=document.getElementById('demoTitle'),note=document.getElementById('demoNote'),stepLabel=document.getElementById('demoStep');if(!board||!watch)return;
const names=['Split','Stack','Switch','Diamond','Clear','Baseline','Triangle','Slingshot','Wave','Reset'];
const notes=['WA and GA split to opposite channels to create two first-pass options.','WA and GA start together then break apart, forcing defenders to choose.','Show one channel, then cross and attack the opposite channel.','Maintain four connected passing options around the ball carrier.','GA clears space to release GS into the primary scoring lane.','GS clears across the circle while GA attacks the baseline-side space.','GS, GA and WA rotate as a three-point passing shape around the circle.','Move wide, switch quickly through centre, then accelerate into attack.','Sequential leads: present, clear and replace so the next receiver arrives on time.','Release pressure backwards or sideways, restore spacing, then rebuild.'];
const base=[[12,50],[27,38],[38,66],[50,50],[62,32],[75,68],[88,50]];
const end=[
[[25,50],[58,34],[70,62],[79,49],[66,30],[80,66],[88,50]],[[24,50],[61,39],[69,58],[78,48],[67,31],[80,65],[88,50]],[[25,50],[64,60],[70,32],[79,50],[67,30],[80,66],[88,50]],[[25,50],[58,35],[67,65],[76,50],[62,29],[79,68],[88,50]],[[87,50],[72,68],[65,43],[57,50],[45,30],[30,67],[15,50]],[[84,65],[76,36],[68,55],[58,49],[45,31],[30,67],[15,50]],[[84,50],[76,67],[70,31],[61,50],[47,31],[31,67],[15,50]],[[28,50],[65,41],[77,24],[81,50],[67,69],[80,66],[88,50]],[[28,50],[63,40],[72,63],[81,49],[68,30],[80,66],[88,50]],[[28,50],[58,40],[70,62],[78,49],[60,28],[78,67],[88,50]]];
const passSets=[[[1,3,2],[2,2,1],[3,1,0]],[[1,3,2],[2,2,1],[3,1,0]],[[1,3,1],[2,1,2],[3,2,0]],[[1,3,2],[2,2,1],[3,1,0]],[[1,3,2],[2,2,1],[3,1,0]],[[1,3,2],[2,2,1],[3,1,0]],[[1,3,2],[2,2,1],[3,1,0]],[[1,3,2],[2,2,3],[3,3,1],[4,1,0]],[[1,3,2],[2,2,1],[3,1,0]],[[1,3,2],[2,2,3],[3,3,1],[4,1,0]]];
const plays=names.map((name,i)=>{const frames=[];for(let s=0;s<5;s++){const f=s/4;frames.push(base.map((p,j)=>[p[0]+(end[i][j][0]-p[0])*f,p[1]+(end[i][j][1]-p[1])*f]))}return{name:`${String(i+1).padStart(2,'0')} · ${name}`,note:notes[i],frames,passes:passSets[i],dur:6000}});
let pi=0,si=0,running=false,raf=null,startAt=0;const ball=document.createElement('div');ball.className='demo-ball';board.appendChild(ball);const tokens=()=>[...board.querySelectorAll('.token:not(.defender-token)')].slice(0,7),portrait=()=>matchMedia('(orientation:portrait)').matches&&matchMedia('(max-width:520px)').matches,tx=p=>portrait()?{x:p[1],y:p[0]}:{x:p[0],y:p[1]},mix=(a,b,f)=>a+(b-a)*f;
plays.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=p.name;select?.appendChild(o)});
function setFrame(idx){const p=plays[pi],fr=p.frames[idx];tokens().forEach((t,i)=>{const q=tx(fr[i]);t.style.left=q.x+'%';t.style.top=q.y+'%'});si=idx;panel.hidden=false;title.textContent=p.name;note.textContent=p.note;stepLabel.textContent=`Step ${idx+1} of ${p.frames.length} · ${idx===0?'Starting shape':idx===p.frames.length-1?'Finish / scoring option':'Developing phase'}`;ball.style.display='none'}
function animate(now){if(!running)return;const p=plays[pi],e=now-startAt;if(e>=p.dur){running=false;watch.querySelector('b').textContent='Watch';setFrame(p.frames.length-1);return}const span=p.dur/(p.frames.length-1),idx=Math.min(3,Math.floor(e/span)),f=(e-idx*span)/span,a=p.frames[idx],b=p.frames[idx+1];tokens().forEach((t,i)=>{const q=tx([mix(a[i][0],b[i][0],f),mix(a[i][1],b[i][1],f)]);t.style.left=q.x+'%';t.style.top=q.y+'%'});stepLabel.textContent=`Playing · phase ${idx+1}/${p.frames.length-1}`;let shown=false;p.passes.forEach(([phase,from,to])=>{const pt=phase*span-350,d=500;if(e>=pt&&e<=pt+d&&!shown){const aa=tx(a[from]),bb=tx(b[to]),pf=(e-pt)/d;ball.style.left=mix(aa.x,bb.x,pf)+'%';ball.style.top=mix(aa.y,bb.y,pf)+'%';ball.style.display='block';shown=true}});if(!shown)ball.style.display='none';raf=requestAnimationFrame(animate)}
function stop(){running=false;if(raf)cancelAnimationFrame(raf);ball.style.display='none';watch.querySelector('b').textContent='Watch'}function choose(i){stop();pi=(i+plays.length)%plays.length;si=0;if(select)select.value=pi;setFrame(0)}
select?.addEventListener('change',()=>choose(Number(select.value)));watch.addEventListener('click',()=>{if(running){stop();return}running=true;startAt=performance.now();watch.querySelector('b').textContent='Pause';panel.hidden=false;title.textContent=plays[pi].name;note.textContent=plays[pi].note;raf=requestAnimationFrame(animate)});step?.addEventListener('click',()=>{stop();setFrame(Math.min(plays[pi].frames.length-1,si+1))});back?.addEventListener('click',()=>{stop();setFrame(Math.max(0,si-1))});next?.addEventListener('click',()=>choose(pi+1));choose(0);
})();