const KEY='fastflow-state-v1';
let deferredPrompt=null,tick=null;
const $=id=>document.getElementById(id);
const pad=n=>String(n).padStart(2,'0');
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return {}}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
function showTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.bottomnav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));scrollTo({top:0,behavior:'smooth'})}
function mins(t){const [h,m]=t.split(':').map(Number);return h*60+m}
function timeFrom(total){total=(total+1440)%1440;return `${pad(Math.floor(total/60))}:${pad(total%60)}`}
function syncEndTime(){const start=$('fastStart').value||'20:00',hours=Number($('fastHours').value||16);$('fastEnd').value=timeFrom(mins(start)+hours*60)}
function recommendPlan(){const exp=$('experience').value,goal=$('goal').value,training=$('training').value;let h=exp==='new'?12:exp==='some'?14:16;if(goal==='weight'&&exp!=='new')h+=2;if(training==='high')h=Math.min(h,16);h=Math.max(12,Math.min(18,h));$('fastHours').value=String(h);syncEndTime();const style=`${h}:${24-h}`;$('recommendation').innerHTML=`<strong>Recommended starting point: ${style}</strong><br>Use this for 2–3 weeks, then adjust based on energy, sleep, training and adherence.`;$('recommendation').classList.remove('hidden')}
function savePlan(){const s=load();s.plan={hours:Number($('fastHours').value),start:$('fastStart').value,end:$('fastEnd').value,lead:Number($('lead').value)};save(s);renderSchedule();notify('Plan saved',`${s.plan.hours}:${24-s.plan.hours} fasting schedule saved.`)}
function startFast(){const s=load(),hours=s.plan?.hours||Number($('fastHours')?.value||16),start=Date.now();s.active={start,end:start+hours*3600000,hours};save(s);runTimer();notify('Fast started',`Your ${hours}-hour fast has started.`)}
function endFast(){const s=load();delete s.active;save(s);runTimer();notify('Fast ended','FastFlow has stopped the timer.')}
function runTimer(){clearInterval(tick);const draw=()=>{const s=load(),a=s.active;if(!a){$('timerText').textContent='Not started';$('timerLabel').textContent='Create a plan first';$('ring').style.setProperty('--progress','0%');return}const now=Date.now(),left=Math.max(0,a.end-now),elapsed=Math.max(0,now-a.start),pct=Math.min(100,(elapsed/(a.end-a.start))*100);if(left<=0){$('timerText').textContent='Complete';$('timerLabel').textContent='You reached your target';$('ring').style.setProperty('--progress','100%');return}const h=Math.floor(left/3600000),m=Math.floor(left%3600000/60000),sec=Math.floor(left%60000/1000);$('timerText').textContent=`${pad(h)}:${pad(m)}:${pad(sec)}`;$('timerLabel').textContent=`${a.hours}-hour fast in progress`;$('ring').style.setProperty('--progress',`${pct}%`)};draw();tick=setInterval(draw,1000)}
function renderSchedule(){const p=load().plan;if(!p){$('todaySchedule').innerHTML='<p class="section-copy">No plan saved yet.</p>';return}$('todaySchedule').innerHTML=`<div class="schedule"><div><strong>Fast starts</strong><small>${p.start}</small></div><span class="tag">Daily</span></div><div class="schedule"><div><strong>Eating window opens</strong><small>${p.end}</small></div><span class="tag">${24-p.hours} hours</span></div>`;$('fastHours').value=String(p.hours);$('fastStart').value=p.start;$('fastEnd').value=p.end;$('lead').value=String(p.lead??30)}
async function enableNotifications(){if(!('Notification'in window))return alert('Notifications are not supported in this browser.');const r=await Notification.requestPermission();alert(r==='granted'?'Notifications enabled.':'Notifications were not enabled.')}
function notify(title,body){if('Notification'in window&&Notification.permission==='granted'){navigator.serviceWorker?.ready.then(reg=>reg.showNotification(title,{body,icon:'icons/icon.svg',badge:'icons/icon.svg'})).catch(()=>new Notification(title,{body}))}}
function testNotification(){notify('FastFlow test','Notifications are working while your device allows them.');if(Notification.permission!=='granted')enableNotifications()}
function icsDate(d){return d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}
function downloadCalendar(){const p=load().plan||{start:$('fastStart').value,end:$('fastEnd').value,hours:Number($('fastHours').value),lead:Number($('lead').value)};const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//VirtualHowTo//FastFlow//EN','CALSCALE:GREGORIAN'];for(let i=0;i<30;i++){const day=new Date();day.setDate(day.getDate()+i);for(const [title,t] of [['FastFlow: start fasting',p.start],['FastFlow: eating window opens',p.end]]){const [h,m]=t.split(':').map(Number),d=new Date(day.getFullYear(),day.getMonth(),day.getDate(),h,m),alarm=Math.max(0,p.lead||0);lines.push('BEGIN:VEVENT',`UID:${Date.now()}-${i}-${h}-${m}@fastflow`,`DTSTAMP:${icsDate(new Date())}`,`DTSTART:${icsDate(d)}`,`DTEND:${icsDate(new Date(d.getTime()+15*60000))}`,`SUMMARY:${title}`,'BEGIN:VALARM',`TRIGGER:-PT${alarm}M`,'ACTION:DISPLAY',`DESCRIPTION:${title}`,'END:VALARM','END:VEVENT')}}lines.push('END:VCALENDAR');const blob=new Blob([lines.join('\r\n')],{type:'text/calendar'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fastflow-reminders.ics';a.click();URL.revokeObjectURL(a.href)}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
syncEndTime();renderSchedule();runTimer();
